
GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTMyNzMyNjEsImV4cCI6MTcxMzI3MzI3NiwiYXVkIjoiNjYxN2QzM2EyNDk1ZmE3Y2E3ZjRiYjEzIiwiaXNzIjoid2Vic2l0ZS5jb20ifQ.7Av1M5G_xzyu046OVUcI_JSExZ0XAv1yqMLmM0C2cqw

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "try1@gmail.com",
    "password": "1234"
}
### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "try@gmail.com",
    "password": "1234"
}


### Refresh-Token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTMyNzM2NTQsImV4cCI6MTc0NDgzMTI1NCwiYXVkIjoiNjYxN2QzM2EyNDk1ZmE3Y2E3ZjRiYjEzIiwiaXNzIjoid2Vic2l0ZS5jb20ifQ.BdC5vEalQTjPk9CnKHKuGsH_qsY6bpbTphwjkKlZ8BE"
}
### Logout
DELETE http://localhost:3000/auth/logout
